language: node_js
node_js:
  - '0.11'
before_script:
  - npm install -g bower grunt-cli
  - bower install --allow-root
  - npm install
services: mongodb
notifications:
     email:
         recipients:
             - sojharo@gmail.com
             - shabir.saba@gmail.com
             - testing@cloudkibo.com
         on_success: change
         on_failure: always

cache: true
